version: '3.8'

services:
  web:
    image: 2fit-api
    build: .
    command: gunicorn -w 4 -b :80 --access-logfile - --error-logfile - --log-level debug src.app:app
    volumes:
      - .:/home/site/wwwroot
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - GUNICORN_CMD_ARGS=--log-level=debug
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: