name: Bump version and deploy to ACR

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    outputs:
      version: ${{ steps.commitizen.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0

      - name: Create bump and changelog
        id: commitizen
        uses: commitizen-tools/commitizen-action@main
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Store version in environment file
        run: echo "VERSION=${{ steps.commitizen.outputs.version }}" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: bump-version
    env:
      VERSION: ${{ env.VERSION }}
      ACR_NAME: 2fitness
      IMAGE_NAME: 2fit-api
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build and push Docker image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$VERSION
